# Generated by Django 5.0.2 on 2024-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_session_bank_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bet',
            field=models.PositiveIntegerField(choices=[(10, '10'), (20, '25'), (50, '50'), (75, '75'), (100, '100')], default=0),
        ),
    ]
