# Generated by Django 5.0.2 on 2024-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_alter_game_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dealer_hand',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_hand',
            field=models.JSONField(default=[]),
        ),
    ]
