# Generated by Django 5.0.2 on 2024-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_alter_game_dealer_hand_alter_game_player_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
