# Generated by Django 5.0.2 on 2024-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0005_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.TextField(default='["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"]'),
        ),
        migrations.AlterField(
            model_name='game',
            name='dealer_hand',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_hand',
            field=models.JSONField(default={}),
        ),
    ]
