# Generated by Django 5.0.2 on 2024-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_game_deck_alter_game_dealer_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dealer_hand',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_hand',
            field=models.JSONField(default=list),
        ),
    ]
