# Generated by Django 5.0.2 on 2024-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0007_alter_game_dealer_hand_alter_game_player_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bet',
            field=models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (75, '75'), (100, '100')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
